name: Daily Weather Notification

on:
  schedule:
    - cron: '55 2 * * *'  # 5:55 по Киеву (UTC+3)
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Если у тебя нет requirements.txt — можно убрать следующую строку
        pip install requests

    - name: Run weather notification script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
      run: python weather_bot.py
